[[constraint]]
  name = "github.com/goshield/middlewares"
  version = "1.x"

[[constraint]]
  name = "github.com/goshield/tools"
  version = "1.x"

[[constraint]]
  name = "github.com/julienschmidt/httprouter"
  version = "1.2"

[prune]
  go-tests = true
  unused-packages = true
